# Even Fibonacci Numbers
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fib = 0                 # initialize a variable for the while loop that creates the Fibonacci sequence
fibonacci = [1,2]       # list to hold the Fibonacci sequence. Initalized with first two digits to get it started.
evens = []              # list that holds only the even numbers of the Fibonacci sequence

while fib < 4000000:                        # create the Fibonacci sequence and add it to the fibonacci[] list
    fib = fibonacci[-1] + fibonacci[-2]
    fibonacci.append(fib)

for i in fibonacci:                         # find only the even numbers in fibonacci[] list and add them to the evens[] list
    if i%2 == 0:
        evens.append(i)

print sum(evens)                            # print the sum of the elemens of the evens[] list
